### ISSUE TITLE
Teku Validator client unable to find keys 

### ISSUE THREAD

**Issue by GLCNI** [NethermindEth/sedge#174]
**Describe the bug**
Teku Validator client unable to find validator keys 

**To Reproduce**
Start Sedge with network Gnosis and Teku for CL client. once synced start the validator.  

had sedge started up a day ago, EL and CL clients synced okay. prompted to start the validator (at this point did not generate keys yet)
Not able to access the 'validator-data' folder until I changed permissions 
![image](https://user-images.githubusercontent.com/67609618/203368438-cf640f80-1497-4c8b-83c5-1c5720670910.png)

**keys generated** restart validator client
`sedge keys --network gnosis`
places keys in `./keystore/validator_keys` and password.txt in `./keystore`

Teku is looking for keys in `--validator-keys=/data/keys:/data/passwords`
I think Teku requires password file per validator with same name structure but `.txt` extension 
![image](https://user-images.githubusercontent.com/67609618/203369116-73372b81-acf5-425e-b217-27c464bebcca.png)

**Tried to Import validators** 
ran the container to import the keys, and restarted the validator client 
same error and looks like the validators are imported to 
`./validator-data/validators`
![image](https://user-images.githubusercontent.com/67609618/203369643-1ba8b04d-a2d6-483e-ac82-80f68a408b67.png)

**Comment by stdevMac** [comment]
Hello @GLCNI, we are looking into your issue now! 

Could you please provide us the `docker-compose.yml` file under the `docker-compose-scripts` folder?

**Comment by GLCNI** [comment]
docker-compose.yml
```
version: "3.9"
services:
  execution:
    stop_grace_period: 30s
    container_name: execution-client
    restart: unless-stopped
    image: ${EC_IMAGE_VERSION}
    networks:
    - sedge
    volumes:
    - ${EC_DATA_DIR}:/nethermind/data
    - ${EC_JWT_SECRET_PATH}:/tmp/jwt/jwtsecret
    ports:
    - 30303:30303/tcp
    - 30303:30303/udp
    expose:
    - 8545
    - 8551
    command:
    - --config=${EL_NETWORK}
    - --datadir=/nethermind/data
    - --log=${NETHERMIND_LOG_LEVEL}
    - --Sync.SnapSync=${EC_SNAP_SYNC_ENABLED}
    - --JsonRpc.Enabled=true
    - --JsonRpc.Host=0.0.0.0
    - --JsonRpc.Port=8545
    - --JsonRpc.EnabledModules=${EC_ENABLED_MODULES}
    - --JsonRpc.JwtSecretFile=/tmp/jwt/jwtsecret
    - --JsonRpc.EngineHost=0.0.0.0
    - --JsonRpc.EnginePort=8551
    - --Network.DiscoveryPort=30303
    - --HealthChecks.Enabled=${NETHERMIND_HEALTH_CHECKS_ENABLED}
    - --Pruning.CacheMb=${NETHERMIND_PRUNING_CACHEMB}
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
  consensus:
    stop_grace_period: 30s
    container_name: consensus-client
    restart: unless-stopped
    image: ${CC_IMAGE_VERSION}
    networks:
    - sedge
    volumes:
    - ${CC_DATA_DIR}:/var/lib/teku
    - ${CC_JWT_SECRET_PATH}:/tmp/jwt/jwtsecret
    ports:
    - 9000:9000/tcp
    - 9000:9000/udp
    - 5054:5054/tcp
    expose:
    - 4000
    command:
    - --log-destination=CONSOLE
    - --logging=${CC_LOG_LEVEL}
    - --network=${CL_NETWORK}
    - --p2p-discovery-bootnodes=${CL_BOOTNODES}
    - --p2p-enabled=true
    - --p2p-port=9000
    - --p2p-peer-upper-bound=${CC_PEER_COUNT}
    - --rest-api-enabled=true
    - --rest-api-host-allowlist=*
    - --rest-api-interface=0.0.0.0
    - --rest-api-port=4000
    - --rest-api-cors-origins=*
    - --rest-api-docs-enabled=false
    - --data-beacon-path=/var/lib/teku/beacon
    - --data-path=/var/lib/teku
    - --data-storage-archive-frequency=2048
    - --data-storage-mode=PRUNE
    - --data-storage-non-canonical-blocks-enabled=false
    - --ee-endpoint=${EC_AUTH_URL}
    - --validators-proposer-default-fee-recipient=${CL_FEE_RECIPIENT}
    - --ee-jwt-secret-file=/tmp/jwt/jwtsecret
    - --metrics-enabled=true
    - --metrics-host-allowlist=*
    - --metrics-interface=0.0.0.0
    - --metrics-port=5054
    - --initial-state=${CHECKPOINT_SYNC_URL}/eth/v2/debug/beacon/states/finalized
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
  validator-import:
    container_name: validator-import-client
    build:
      context: github.com/NethermindEth/teku-init-validator
    volumes:
    - ${VL_DATA_DIR}:/data
    - ${KEYSTORE_DIR}:/keystore
  validator:
    container_name: validator-client
    image: ${VL_IMAGE_VERSION}
    depends_on:
      validator-import:
        condition: service_completed_successfully
    networks:
    - sedge
    ports:
    - 5056:5056
    volumes:
    - ${VL_DATA_DIR}:/data
    command:
    - validator-client
    - --beacon-node-api-endpoint=${CC_API_URL}
    - --data-path=/data
    - --log-destination=CONSOLE
    - --validators-graffiti=${GRAFFITI}
    - --validator-keys=/data/keys:/data/passwords
    - --metrics-enabled=true
    - --metrics-host-allowlist=*
    - --metrics-interface=0.0.0.0
    - --metrics-port=5056
    - --validators-proposer-default-fee-recipient=${CL_FEE_RECIPIENT}
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
networks:
  sedge:
    name: sedge_network
```

.env file
```
# --- Global configuration ---
EL_NETWORK=xdai
CL_NETWORK=gnosis
# --- Execution Layer - Execution Node - configuration ---
EC_IMAGE_VERSION=nethermind/nethermind:1.14.3
NETHERMIND_LOG_LEVEL=INFO
EC_ENABLED_MODULES=[Web3,Eth,Subscribe,Net,]
EC_METRICS_ENABLED=false
EC_NODENAME=Nethermind
NETHERMIND_METRICS_PUSH_GATEWAY_URL=http://localhost:9090/metrics
NETHERMIND_HEALTH_CHECKS_ENABLED=false
NETHERMIND_PRUNING_CACHEMB=2048
EC_DATA_DIR=./execution-data
EC_SNAP_SYNC_ENABLED=false
EC_JWT_SECRET_PATH=/home/glc/docker-compose-scripts/jwtsecret
# --- Consensus Layer - Beacon Node - configuration ---
CC_PEER_COUNT=50
CC_LOG_LEVEL=info
EC_API_URL=http://execution:8545
EC_AUTH_URL=http://execution:8551
CC_INSTANCE_NAME=Teku
CC_IMAGE_VERSION=consensys/teku:22.9.0
CC_DATA_DIR=./consensus-data
CC_JWT_SECRET_PATH=/home/glc/docker-compose-scripts/jwtsecret
CL_FEE_RECIPIENT=< >
CL_BOOTNODES="enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCC>
CHECKPOINT_SYNC_URL=https://rpc-gbc.gnosischain.com
# --- Consensus Layer - Validator Node - configuration ---
CC_API_URL=http://consensus:4000
GRAFFITI=nethermind-teku
VL_LOG_LEVEL=info
VL_INSTANCE_NAME=TekuValidator
VL_IMAGE_VERSION=consensys/teku:22.9.0
KEYSTORE_DIR=./keystore
VL_DATA_DIR=./validator-data
```
