### ISSUE TITLE
Lodestar Validator Client unable to find keys: gnosischain

### ISSUE THREAD

**Issue by GLCNI** [NethermindEth/sedge#175]
**Describe the bug**
Lodestar Validator client unable to find validator keys: `No signers found with current args `

![image](https://user-images.githubusercontent.com/67609618/203818656-f57d6264-a581-4ee3-9d8d-d7976fe33457.png)

Fixed by running validator import manually 

![image](https://user-images.githubusercontent.com/67609618/203821444-c7d1d9a3-d958-413b-8305-961df1c99aae.png)

**To Reproduce**
Sedge CLI
`sedge cli --network gnosis -c lodestar -e nethermind`

Keys Generated 
`sedge keys --network gnosis --eth1-withdrawal-address <my address>`
Note: keys seem correct, `deposit_data.json` is accepted by the deposit UI, (with edit mentioned here https://github.com/NethermindEth/sedge/issues/168)

EL and CL Synced and prompted to run the validator, but validator import service is skipped 

**Additional Info**
Generated Scripts

```

  validator-import:
    container_name: validator-import-client
    image: ${VL_IMAGE_VERSION}
    networks:
    - sedge
    volumes:
    - ${KEYSTORE_DIR}:/keystore
    - ${VL_DATA_DIR}:/data
    command: |-
      validator import
      --network=${CL_NETWORK}
      --dataDir=/data
      --importKeystores=/keystore/validator_keys
      --importKeystoresPassword=/keystore/keystore_password.txt
  validator:
    container_name: validator-client
    image: ${VL_IMAGE_VERSION}
    networks:
    - sedge
    ports:
    - 5056:5056
    volumes:
    - ${VL_DATA_DIR}:/data/validator
    command:
    - validator
    - --network=${CL_NETWORK}
    - --dataDir=/data/validator
    - --logFile=/data/validator/logs/validator.log
    - --logFileLevel=${VL_LOG_LEVEL}
    - --server=${CC_API_URL}
    - --metrics=true
    - --metrics.address=0.0.0.0
    - --metrics.port=5056
    - --suggestedFeeRecipient=${CL_FEE_RECIPIENT}
    - --graffiti=${GRAFFITI}
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
networks:
  sedge:
    name: sedge_network
```

.env vars

```
# --- Global configuration ---
EL_NETWORK=xdai
CL_NETWORK=gnosis
# --- Execution Layer - Execution Node - configuration ---
EC_IMAGE_VERSION=nethermind/nethermind:1.14.3
NETHERMIND_LOG_LEVEL=INFO
EC_ENABLED_MODULES=[Web3,Eth,Subscribe,Net,]
EC_METRICS_ENABLED=false
EC_NODENAME=Nethermind
NETHERMIND_METRICS_PUSH_GATEWAY_URL=http://localhost:9090/metrics
NETHERMIND_HEALTH_CHECKS_ENABLED=false
NETHERMIND_PRUNING_CACHEMB=2048
EC_DATA_DIR=./execution-data
EC_SNAP_SYNC_ENABLED=false
EC_JWT_SECRET_PATH=/home/glc/docker-compose-scripts/jwtsecret
# --- Consensus Layer - Beacon Node - configuration ---
CC_PEER_COUNT=50
CC_LOG_LEVEL=info
CC_LODESTAR_PRESET=gnosis
EC_API_URL=http://execution:8545
EC_AUTH_URL=http://execution:8551
CC_INSTANCE_NAME=Lodestar
CC_IMAGE_VERSION=chainsafe/lodestar:v1.1.1
CC_DATA_DIR=./consensus-data
CC_JWT_SECRET_PATH=/home/glc/docker-compose-scripts/jwtsecret
CL_FEE_RECIPIENT=< ..MY ADDRESS. >
CL_BOOTNODES="enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCC>
CHECKPOINT_SYNC_URL=https://rpc-gbc.gnosischain.com
# --- Consensus Layer - Validator Node - configuration ---
CC_API_URL=http://consensus:4000
GRAFFITI=nethermind-lodestar
VL_LOG_LEVEL=info
VL_INSTANCE_NAME=LodestarValidator
VL_IMAGE_VERSION=chainsafe/lodestar:v1.1.1
KEYSTORE_DIR=./keystore
VL_DATA_DIR=./validator-data
```
