### ISSUE TITLE
Prysm and Lodestar template misconfiguration

### ISSUE THREAD

**Issue by AntiD2ta** [NethermindEth/sedge#176]
**Describe the bug**
Both validator templates for Prysm and Lodestar are missing the `depends_on` property that allows the script to start the `validator` container only if the `validator-import` one ran successfully.

This can be solve adding the following to the `validator` service template:
```yaml
depends_on: 
      validator-import:
        condition: service_completed_successfully
```
